/*

1. Các tạo View: >=4 lệnh
	THONG KE MAT HANG BAN CHAY NHAT TOP (10) TRONG THANG
	THONG KE LUONG THANG
	THONG KE TONG CAC HOA DON BAN VA TONG GIA TRI CAC HOA DON BAN
	THONG KE TONG CAC HOA DON NHAP VA TONG GIA TRI CAC HOA DON NHAP
2. Các câu lệnh trigger: >=4 lệnh
	CAP NHAT LAI SO LUONG NGUYEN LIEU MOI KHI BAN HANG
	CAP NHAT LAI SO LUONG NGUYEN LIEU SAU KHI NHAP HANG
	CAP NHAT LAI SO LUONG NGUYEN LIEU MOI KHI NHAP HANG 
	KIEM TRA DU LIEU DAU VAO SO LUONG NHAP HANG > 0 
	CAP NHAT TRUONG STATUS KHI NHAN VIEN NGHI VIEC
3. Các thủ tục (Stored Procedure) >=4 thủ tục
	TIM KIEM CAC KHANH HANG CO DIA CHI TAI HA NOI TU TEN HOAC MA KHANH HANG
	DUA RA THONG TIN CUA HOA DON BAN  TU MA HOA DON BAN 
	DUA RA THONG TIN CUA HOA DON NHAP TU MA HOA DON NHAP VA MA NHA CUNG CAP
	DUA RA THONG TIN CUA NHAN VIEN TU MA NHAN VIEN
4. Các hàm (UDFs): >= 4 hàm
	HAM TINH TONG TIEN CUA HOA DON BAN TU MA HOA DON BAN
	HAM TINH TONG TIEN CUA HOA DON NHAP TU HOA DON NHAP 
	HAM TINH DOANH THU TRONG THANG TU HOA DON BAN VA HOA DON NHAP
	HAM KIEM TRA TAI KHOAN LOGIN
5. Các câu lệnh ngôn ngữ điều khiển dữ liệu: >=2 lệnh

Kiem tra login 
KIEM TRA XEM SO DONG TRA VE . 
NEU > 0 THI LA CO TAI KHOAN .	
	DANG NHAP THANH CONG THI HIEN THONG BAO DANG NHAP THANH CONG 
	GIAO DIEN ADMIN SE BAO GOM TAT CA CAC THONG TIN, KHI DANG NHAP SE KIEM TRA XEM CO QUYEN NHU THE NAO THI SE CHO PHEP THAO TAC
NEU = 0 THI LA KHONG CO TAI KHOAN.
	THONG BAO TAI KHOAN KHONG TON TAI
*/

select * from taikhoan 

